database_dsn: |
 pgsql:
 user=carnivora_edentata
 host=carnvivora.server.example
 dbname=carnivora

modules_nav:
 - email
 - email_list
 - jabber
 - dns
 - server_access
 - web

base_url: '/edentata/'
support_url: 'mailto:support@domain.example'

